# Generated by Django 4.2.16 on 2025-10-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='userAuth_ro_name_d38340_idx'),
        ),
    ]
