# Generated by Django 4.2.16 on 2025-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locked_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
