# Generated by Django 4.2.16 on 2025-04-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number2', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('nok_phonenumber', models.CharField(max_length=20)),
                ('motorcycle_type', models.CharField(max_length=10)),
                ('motorcycle_brand', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('guarantor1', models.CharField(max_length=50)),
                ('guarantor1_number', models.CharField(max_length=20)),
                ('guarantor2', models.CharField(max_length=50)),
                ('guarantor2_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Riders Profile',
            },
        ),
    ]
