# Generated by Django 4.2.16 on 2025-04-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number2', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20)),
                ('nok', models.CharField(max_length=50)),
                ('nok_phonenumber', models.CharField(max_length=20)),
                ('motorcycle_type', models.CharField(max_length=10)),
                ('motorcycle_brand', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('guarantor1', models.CharField(max_length=50)),
                ('guarantor1_number', models.CharField(max_length=20)),
                ('guarantor2', models.CharField(max_length=50)),
                ('guarantor2_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Riders Profile',
            },
            bases=('users.customuser',),
        ),
    ]
