# Generated by Django 4.2.16 on 2025-06-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Riders',
        ),
    ]
