# Generated by Django 4.2.16 on 2025-07-18 16:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RidersProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number2', models.CharField(max_length=20, null=True)),
                ('nin', models.CharField(max_length=20, null=True)),
                ('next_of_kin', models.CharField(max_length=225, null=True)),
                ('nok_phonenumber', models.CharField(max_length=20, null=True)),
                ('motorcycle_type', models.CharField(max_length=225, null=True)),
                ('motorcycle_brand', models.CharField(max_length=225, null=True)),
                ('plate_number', models.CharField(max_length=20, null=True)),
                ('guarantor1', models.CharField(max_length=225, null=True)),
                ('guarantor1_number', models.CharField(max_length=20, null=True)),
                ('guarantor2', models.CharField(max_length=225, null=True)),
                ('guarantor2_number', models.CharField(max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=225, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('account_name', models.CharField(max_length=225, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Riders Profile',
            },
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profile',
            },
        ),
        migrations.CreateModel(
            name='VendorsProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=225, null=True)),
                ('business_location_city', models.CharField(max_length=225, null=True)),
                ('business_location_state', models.CharField(max_length=225, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendors Profile',
            },
        ),
    ]
