# Generated by Django 4.2.16 on 2025-06-06 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_vendorsprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profile'},
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
