# Generated by Django 4.2.16 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsprofile',
            name='business_address',
            field=models.TextField(null=True),
        ),
    ]
