# Generated by Django 4.2.16 on 2025-06-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_usersprofile_options_usersprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridersprofile',
            name='account_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='bank_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='guarantor1',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='guarantor1_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='guarantor2',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='guarantor2_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='motorcycle_brand',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='motorcycle_type',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='next_of_kin',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='nin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='nok_phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='phone_number2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridersprofile',
            name='plate_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
