# Generated by Django 4.2.16 on 2025-09-17 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_category_options'),
        ('profiles', '0003_vendorsprofile_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='favorite_vendors',
            field=models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='viewed_products',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='products.product'),
        ),
    ]
