# Generated by Django 4.2.16 on 2025-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_usersprofile_favorite_vendors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsprofile',
            name='transfer_recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
