# Generated by Django 4.2.16 on 2025-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_ridersprofile_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
