# Generated by Django 4.2.16 on 2025-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_usersprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='business_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
