# Generated by Django 4.2.16 on 2025-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_vendorsprofile_transfer_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorsprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
