# Generated by Django 4.2.16 on 2025-10-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_vendorsprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorsprofile',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=50),
        ),
    ]
