# Generated by Django 4.2.16 on 2025-10-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_vendorsprofile_is_suspended_vendorsprofile_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='business_name',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
