# Generated by Django 4.2.16 on 2025-10-20 07:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_vendorsprofile_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='business_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddConstraint(
            model_name='vendorsprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('business_name'), name='unique_lower_business_name_constraint', violation_error_message='A vendor with this business name already exists.'),
        ),
    ]
