# Generated by Django 4.2.16 on 2025-10-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_vendorsprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorsprofile',
            index=models.Index(fields=['business_name'], name='profiles_ve_busines_f1d299_idx'),
        ),
    ]
