# Generated by Django 4.2.16 on 2025-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_vendorsprofile_profiles_ve_busines_f1d299_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
