# Generated by Django 4.2.16 on 2025-12-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_usersprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersprofile",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersprofile",
            name="phone_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="usersprofile",
            index=models.Index(
                fields=["phone_number"], name="profiles_us_phone_n_25b98a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersprofile",
            constraint=models.UniqueConstraint(
                fields=("phone_number",),
                name="unique_phone_number_constraint",
                violation_error_message="This phone number is already registered.",
            ),
        ),
    ]
