# Generated by Django 4.2.16 on 2025-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_usersprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='phone_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]