# Generated by Django 4.2.16 on 2025-07-28 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assigned_riders',
            field=models.ManyToManyField(blank=True, help_text='Multiple riders can be assigned to an Order item to either accept or decline it', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rider',
            field=models.ForeignKey(help_text='The rider that accept the Order will be registered here and be responsible for delivering it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
