# Generated by Django 4.2.16 on 2025-07-28 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_orderitem_assigned_riders_orderitem_picked_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='assigned_riders',
            field=models.ManyToManyField(help_text='Multiple riders can be assigned to an Order item to either accept or decline it', to=settings.AUTH_USER_MODEL),
        ),
    ]
