# Generated by Django 4.2.16 on 2025-09-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
        ('orders', '0006_orderitem_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
