# Generated by Django 4.2.16 on 2025-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_locked',
            field=models.BooleanField(default=False),
        ),
    ]
