branch-defaults:
  dev:
    environment: null
  prod:
    environment: LagBuy-Backend
    group_suffix: null
environment-defaults:
  django-backend-env:
    branch: null
    repository: null
global:
  application_name: LagBuy-Backend-env
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12
  default_region: af-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
