# Generated by Django 4.2.16 on 2025-12-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_orderitem_stock_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferallWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Wallet',
                'verbose_name_plural': 'Referral Wallets',
            },
        ),
        migrations.CreateModel(
            name='ReferralWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('addition', 'Addition'), ('deduction', 'Deduction'), ('pending', 'Pending')], max_length=20)),
                ('bonus_usage_type', models.CharField(choices=[('product', 'Product Purchase'), ('service', 'Service Charge')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_wallet_transactions', to='orders.order')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='referral.referallwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type'], name='referral_re_transac_57c073_idx'), models.Index(fields=['bonus_usage_type'], name='referral_re_bonus_u_8a8348_idx')],
            },
        ),
    ]
