# Generated by Django 4.2.16 on 2025-12-17 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferallWallet',
            new_name='ReferralWallet',
        ),
    ]
