# Generated by Django 4.2.16 on 2026-01-03 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_rename_referallwallet_referralwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='total_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
