# Generated by Django 4.2.16 on 2026-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_referralwallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralwallettransaction',
            name='bonus_usage_type',
            field=models.CharField(choices=[('product', 'Product Purchase'), ('service', 'Service Charge')], max_length=20, null=True),
        ),
    ]
