# Generated by Django 4.2.16 on 2026-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_alter_referralwallettransaction_bonus_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralwallet',
            name='product_bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referralwallet',
            name='service_bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
