# Generated by Django 4.2.16 on 2024-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='status',
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(related_name='coupons', to='products.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
