# Generated by Django 4.2.16 on 2025-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='max_puchase_amount',
            new_name='max_purchase_quantity',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='min_purchase_amount',
            new_name='min_purchase_quantity',
        ),
    ]
