# Generated by Django 4.2.16 on 2025-05-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='products',
        ),
    ]
