# Generated by Django 4.2.16 on 2025-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
