# Generated by Django 4.2.16 on 2025-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payoutrequest_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet_credited',
            field=models.BooleanField(default=False),
        ),
    ]
