# Generated by Django 4.2.16 on 2025-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vendor's remaining wallet balance after payout request.", max_digits=15, null=True),
        ),
    ]
