# Generated by Django 4.2.16 on 2025-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
    ]
