# Generated by Django 4.2.16 on 2025-06-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_role_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
