# Generated by Django 4.2.16 on 2025-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_exportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
