# Generated by Django 4.2.16 on 2024-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'buyer'), name='unique_review_per_product_per_user'),
        ),
    ]
