# Generated by Django 4.2.16 on 2025-10-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
        ("notifications", "0002_webhookevent"),
    ]

    operations = []
